### PR TITLE
Docs: github-action.md: fix wording

### PR DESCRIPTION
**Pull request by lolmaus**

### CODE REVIEW

**Review by chrmarti — APPROVED** [review]
Thanks!

**Review by bpasero — APPROVED** [review]

**Review by dbaeumer — APPROVED** [review]

**Comment by chrmarti** [comment]
/test-force-approve

docs only changes

**Comment by chrmarti** [comment]
/test-force-approve

docs only changes

**Comment by chrmarti** [comment]
Sorry for the spam, working out a permissions issue with CI.

**Comment by chrmarti** [comment]
/test-force-approve

docs only changes

**Pull request merged**
