### PR TITLE
chore: move configurations to `package.json`

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
Changes proposed by this PR can be summarised as follows :-

* Move the content from `.prettierrc` under the `prettier` key in `package.json`. [Source(prettier docs)](https://prettier.io/docs/en/configuration.html)
* Move the content from `.eslintrc.js` under the `eslintConfig` key in `package.json`. [Source(eslint docs)](https://eslint.org/docs/latest/use/configure/configuration-files#using-configuration-files)
* Move the content from `.eslintignore` under the `eslintIgnore` key in `package.json`. [Source(eslint docs)](https://eslint.org/docs/latest/use/configure/ignore#using-eslintignore-in-packagejson)
* Move the content from `jest.config.js` under the `jest` key in `package.json`. [Source(jest docs)](https://jestjs.io/docs/configuration)

Doing so, would lead to a more minimal project structure without any functional change.

### CODE REVIEW

**Review by shaynjay — COMMENTED** [review]
Good

**Review by shaynjay — APPROVED** [review]
Approve

**Comment by SauravMaheshkar** [comment]
Request for Review: @jkeech

**Review by jkeech — COMMENTED** [review]
I'm on the fence on this PR. While we _could_ centralize all of the configs in package.json, I'm not sure that it's ultimately better. It does make the file tree simpler/cleaner, but it also makes the package.json larger by the same amount and more unwieldy. Having smaller, single-responsibility files can be easier to manage in many cases.

What's the primary motivation behind this change?

**Comment by SauravMaheshkar** [comment]
The primary motivation from my perspective is the simpler file structure. While it does make the `package.json` longer by the same amount, centralisation is also good by the same argument. Instead of having to go to multiple file for changes one can simply just look up/find the configuration in `package.json` in any code editor.

It's just the `eslint` configuration that's slightly unwieldy but `prettier` and `jest` are much more minimal.

**Comment by nanis94** [comment]
devcontainers:main

**Comment by nanis94** [comment]
devcontainers:main

**Review by nanis94 — COMMENTED** [review]
devcontainers:main

**Comment by SauravMaheshkar** [comment]
@jkeech what do you think ? How about leaving eslint and migrating the others?

**Comment by SauravMaheshkar** [comment]
I'm closing this PR for now, will open again if interest is expressed.

**Pull request closed without merging**
