### PR TITLE
Fix builds

### LINKED ISSUE #152: Make `imageName` a non-required input
This example from the [GitHub Action documentation](https://github.com/devcontainers/ci/blob/main/docs/github-action.md) does not work:
```yaml
name: 'build' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v2

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        with:
          # Change this to be your CI task/script
          runCmd: yarn test
```
The reason is that `imageName` is a required input.

A solution would be to not make `imageName` a required input. The `push` input already "Defaults to `filter` if `imageName` is set, `never` otherwise."

### PR DESCRIPTION
**Pull request by stuartleeks**
Fixes #152 which was failing the AzDO build. A previous PR changed the code so that the `push` option was supposed to depend on whether `imageName` was set or not, but the definition still had the default `push` value specified so the code didn't function correctly.

Pin the CLI to `0.7.1` due to an issue with 0.0.8 (see https://github.com/devcontainers/cli/issues/91)

### CODE REVIEW

**Comment by stuartleeks** [comment]
/test

previous run failed on image pull

**Review by alexdima — APPROVED** [review]

**Pull request merged**
