### PR TITLE
Set-Output/Set-State Deprecation Update

### PR DESCRIPTION
**Pull request by stephenandary**
Update to handle change for set-output and save-state syntax as per: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### CODE REVIEW

**Comment by stephenandary** [comment]
First run was all succesful, will check if anything has been merged to main since later. They were 2 very small changes that should not have made a difference.

**Comment by stuartleeks** [comment]
HI @stephenandary,

Thanks for this. I just kicked off a test run and it failed with [this error](https://github.com/devcontainers/ci/actions/runs/3486746508/jobs/5833576655#step:8:1436):

```
[2022-11-17T08:57:13.985Z] ./scripts/build-package.sh: line 57: $GITHUB_OUTPUT: ambiguous redirect
```

**Comment by stephenandary** [comment]
Thank you, looking at this now. Just need to figure out how to pull this branch so I can update it. Hopefully won't take too long.

**Comment by stephenandary** [comment]
Should I close this?

**Comment by stuartleeks** [comment]
Thanks for the nudge @stephenandary (and apologies for the delay!)

I started looking at your latest change and it looks to me as though `echo '"version_short=$VERSION_MAJOR.$VERSION_MINOR" >> $GITHUB_OUTPUT'` would output `"version_short=$VERSION_MAJOR.$VERSION_MINOR" >> $GITHUB_OUTPUT` to stdout? That said, I don't currently understand the `ambiguous redirect` error from the previous run¬

I guess I'll kick off a run work the workflow and we can test it.

**Comment by stuartleeks** [comment]
Looks like it is outputting the full `"version_short=$VERSION_MAJOR.$VERSION_MINOR" >> $GITHUB_OUTPUT` value: https://github.com/devcontainers/ci/actions/runs/3618501983/jobs/6098442122#step:8:2325 😞

**Comment by stephenandary** [comment]
In my yaml I don't use the surrounding quotes, I am not sure why the previous test failed that didnt have them. Should I try changing up the quotes again? There is another option for where to place quotes. Am I able to run a test myself with /test comment? Or is it possible for me to test change locally before next push?

**Comment by stephenandary** [comment]
I closed the PR for now because it keeps getting stale, and I am not sure what to do. But the warnings are still happening. I am really not sure why the initial PR didn't work. I can try again later, but I am unsure how to test the changes locally before pushing it.

**Pull request closed without merging**
