### PR TITLE
gh: refactor community files

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
This PR aims to move the `CODEOWNERS` and `CONTRIBUTING.md` file from the root of the directory to the `.github/` directory. Github looks for a contribution guideline file in the following order: `.github dir > project root > docs dir` ([source](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)). Moving the file to the `.github/` dir leads to a minimal project structure without any functional change.

### CODE REVIEW

**Comment by stuartleeks** [comment]
I'm happy to move `CODEOWNERS` but my personal feeling is that having `CONTRIBUTING.md` in the root aids discoverability.

@chrmarti  - what are your thoughts?

**Comment by SauravMaheshkar** [comment]
of course, I'll reiterate after feedback.

**Comment by chrmarti** [comment]
> I'm happy to move `CODEOWNERS` but my personal feeling is that having `CONTRIBUTING.md` in the root aids discoverability.

Makes sense! 👍

**Comment by SauravMaheshkar** [comment]
> > I'm happy to move `CODEOWNERS` but my personal feeling is that having `CONTRIBUTING.md` in the root aids discoverability.
> 
> Makes sense! 👍

Addressed in 337124e36a9a80d6522e862c3454a56f8893a29c

**Comment by SauravMaheshkar** [comment]
Gentle ping @stuartleeks @chrmarti

**Review by jkeech — APPROVED** [review]
LGTM. I agree with moving `CODEOWNERS` and not the `CONTRIBUTING.md` guide.

**Pull request merged**
